---
- name: Import SSH moduli task
  import_tasks: moduli.yml
  when: ssh_regenerate_moduli

- name: Ensure sshd uses a hardened config
  template:
    src: "sshd_config.j2"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - reload sshd
    - reload firewalld

- name: Ensure root account is locked
  user:
    name: root
    state: present
    password_lock: true

- name: Ensure firewalld allows updated sshd port.
  template:
    src: "firewalld.ssh.xml.j2"
    dest: /etc/firewalld/services/ssh.xml
    owner: root
    group: root
    mode: 0644
  notify:
    - reload firewalld

#- name: Register host fact that ssh moduli was regenerated
#  set_fact:
#    ssh_regenerate_moduli: false
#    cacheable: true
